language: node_js
node_js:
  - "12.18.2"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng lint news --fix
- npm run test-headless
- ng build --prod --base-href https://github.com/kaushikv070/news

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/news
  on:
    branch: master